# Generated by Django 4.0.6 on 2022-07-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(related_name='restaurants', to='main_app.category'),
        ),
    ]
